// todo: generate this file automatically.

part of 'source_node.dart';

final themeDataNode = SourceNode<ThemeData>('ThemeData', Map.unmodifiable({
  '?#colorScheme': SourceNode<ColorScheme>(),
  '?#brightness': SourceNode<Brightness>(),
  '?#primarySwatch': SourceNode<MaterialColor>(),
  '?#primaryColor': SourceNode<Color>(),
  '?#primaryColorLight': SourceNode<Color>(),
  '?#primaryColorDark': SourceNode<Color>(),
  '?#primaryColorBrightness': SourceNode<Brightness>(),
  '?#accentColor': SourceNode<Color>(),
  '?#accentColorBrightness': SourceNode<Brightness>(),
  '?#elevatedButtonTheme': elevatedButtonThemeDataNode,
  '?#outlinedButtonTheme': outlinedButtonThemeDataNode,
  '?#textButtonTheme': textButtonThemeDataNode,
}));

final colorSchemeFromSwatchNode = SourceNode<ColorScheme>('ColorScheme.fromSwatch', Map.unmodifiable({
  '@!#primarySwatch': SourceNode<MaterialColor>(),
  '?#primaryColorDark': SourceNode<Color>(),
  '?#accentColor': SourceNode<Color>(),
  '?#cardColor': SourceNode<Color>(),
  '?#backgroundColor': SourceNode<Color>(),
  '?#errorColor': SourceNode<Color>(),
  '@!#brightness': SourceNode<Brightness>(),
}));

final colorSchemeLightNode = SourceNode<ColorScheme>('ColorScheme.light', Map.unmodifiable({
  '@!#primary': SourceNode<Color>(),
  '@!#primaryVariant': SourceNode<Color>(),
  '@!#secondary': SourceNode<Color>(),
  '@!#secondaryVariant': SourceNode<Color>(),
  '@!#surface': SourceNode<Color>(),
  '@!#background': SourceNode<Color>(),
  '@!#error': SourceNode<Color>(),
  '@!#onPrimary': SourceNode<Color>(),
  '@!#onSecondary': SourceNode<Color>(),
  '@!#onSurface': SourceNode<Color>(),
  '@!#onBackground': SourceNode<Color>(),
  '@!#onError': SourceNode<Color>(),
  '@!#brightness': SourceNode<Brightness>(),
}));

final colorSchemeDarkNode = SourceNode<ColorScheme>('ColorScheme.dark', Map.unmodifiable({
  '@!#primary': SourceNode<Color>(),
  '@!#primaryVariant': SourceNode<Color>(),
  '@!#secondary': SourceNode<Color>(),
  '@!#secondaryVariant': SourceNode<Color>(),
  '@!#surface': SourceNode<Color>(),
  '@!#background': SourceNode<Color>(),
  '@!#error': SourceNode<Color>(),
  '@!#onPrimary': SourceNode<Color>(),
  '@!#onSecondary': SourceNode<Color>(),
  '@!#onSurface': SourceNode<Color>(),
  '@!#onBackground': SourceNode<Color>(),
  '@!#onError': SourceNode<Color>(),
  '@!#brightness': SourceNode<Brightness>(),
}));

final elevatedButtonThemeDataNode = SourceNode<ElevatedButtonThemeData>('ElevatedButtonThemeData', Map.unmodifiable({
  '?#style': elevatedButtonStyleFromNode,
}));

final outlinedButtonThemeDataNode = SourceNode<OutlinedButtonThemeData>('OutlinedButtonThemeData', Map.unmodifiable({
  '?#style': outlinedButtonStyleFromNode,
}));

final textButtonThemeDataNode = SourceNode<TextButtonThemeData>('TextButtonThemeData', Map.unmodifiable({
  '?#style': textButtonStyleFromNode,
}));

final elevatedButtonStyleFromNode = SourceNode<ButtonStyle>('ElevatedButton.styleFrom', Map.unmodifiable({
  '?#primary': SourceNode<Color>(),
  '?#onPrimary': SourceNode<Color>(),
  '?#onSurface': SourceNode<Color>(),
}));

final outlinedButtonStyleFromNode = SourceNode<ButtonStyle>('OutlinedButton.styleFrom', Map.unmodifiable({
  '?#primary': SourceNode<Color>(),
  '?#onSurface': SourceNode<Color>(),
}));

final textButtonStyleFromNode = SourceNode<ButtonStyle>('TextButton.styleFrom', Map.unmodifiable({
  '?#primary': SourceNode<Color>(),
  '?#onSurface': SourceNode<Color>(),
}));

final _sourceValues = Map<String, dynamic>.unmodifiable(<String, dynamic>{
  'Brightness.light': Brightness.light,
  'Brightness.dark': Brightness.dark,
  'Colors.red': Colors.red,
  'Colors.red.shade50': Colors.red.shade50,
  'Colors.red.shade100': Colors.red.shade100,
  'Colors.red.shade200': Colors.red.shade200,
  'Colors.red.shade300': Colors.red.shade300,
  'Colors.red.shade400': Colors.red.shade400,
  'Colors.red.shade500': Colors.red.shade500,
  'Colors.red.shade600': Colors.red.shade600,
  'Colors.red.shade700': Colors.red.shade700,
  'Colors.red.shade800': Colors.red.shade800,
  'Colors.red.shade900': Colors.red.shade900,
  'Colors.redAccent': Colors.redAccent,
  'Colors.redAccent.shade100': Colors.redAccent.shade100,
  'Colors.redAccent.shade200': Colors.redAccent.shade200,
  'Colors.redAccent.shade400': Colors.redAccent.shade400,
  'Colors.redAccent.shade700': Colors.redAccent.shade700,
  'Colors.pink': Colors.pink,
  'Colors.pink.shade50': Colors.pink.shade50,
  'Colors.pink.shade100': Colors.pink.shade100,
  'Colors.pink.shade200': Colors.pink.shade200,
  'Colors.pink.shade300': Colors.pink.shade300,
  'Colors.pink.shade400': Colors.pink.shade400,
  'Colors.pink.shade500': Colors.pink.shade500,
  'Colors.pink.shade600': Colors.pink.shade600,
  'Colors.pink.shade700': Colors.pink.shade700,
  'Colors.pink.shade800': Colors.pink.shade800,
  'Colors.pink.shade900': Colors.pink.shade900,
  'Colors.pinkAccent': Colors.pinkAccent,
  'Colors.pinkAccent.shade100': Colors.pinkAccent.shade100,
  'Colors.pinkAccent.shade200': Colors.pinkAccent.shade200,
  'Colors.pinkAccent.shade400': Colors.pinkAccent.shade400,
  'Colors.pinkAccent.shade700': Colors.pinkAccent.shade700,
  'Colors.purple': Colors.purple,
  'Colors.purple.shade50': Colors.purple.shade50,
  'Colors.purple.shade100': Colors.purple.shade100,
  'Colors.purple.shade200': Colors.purple.shade200,
  'Colors.purple.shade300': Colors.purple.shade300,
  'Colors.purple.shade400': Colors.purple.shade400,
  'Colors.purple.shade500': Colors.purple.shade500,
  'Colors.purple.shade600': Colors.purple.shade600,
  'Colors.purple.shade700': Colors.purple.shade700,
  'Colors.purple.shade800': Colors.purple.shade800,
  'Colors.purple.shade900': Colors.purple.shade900,
  'Colors.purpleAccent': Colors.purpleAccent,
  'Colors.purpleAccent.shade100': Colors.purpleAccent.shade100,
  'Colors.purpleAccent.shade200': Colors.purpleAccent.shade200,
  'Colors.purpleAccent.shade400': Colors.purpleAccent.shade400,
  'Colors.purpleAccent.shade700': Colors.purpleAccent.shade700,
  'Colors.deepPurple': Colors.deepPurple,
  'Colors.deepPurple.shade50': Colors.deepPurple.shade50,
  'Colors.deepPurple.shade100': Colors.deepPurple.shade100,
  'Colors.deepPurple.shade200': Colors.deepPurple.shade200,
  'Colors.deepPurple.shade300': Colors.deepPurple.shade300,
  'Colors.deepPurple.shade400': Colors.deepPurple.shade400,
  'Colors.deepPurple.shade500': Colors.deepPurple.shade500,
  'Colors.deepPurple.shade600': Colors.deepPurple.shade600,
  'Colors.deepPurple.shade700': Colors.deepPurple.shade700,
  'Colors.deepPurple.shade800': Colors.deepPurple.shade800,
  'Colors.deepPurple.shade900': Colors.deepPurple.shade900,
  'Colors.deepPurpleAccent': Colors.deepPurpleAccent,
  'Colors.deepPurpleAccent.shade100': Colors.deepPurpleAccent.shade100,
  'Colors.deepPurpleAccent.shade200': Colors.deepPurpleAccent.shade200,
  'Colors.deepPurpleAccent.shade400': Colors.deepPurpleAccent.shade400,
  'Colors.deepPurpleAccent.shade700': Colors.deepPurpleAccent.shade700,
  'Colors.indigo': Colors.indigo,
  'Colors.indigo.shade50': Colors.indigo.shade50,
  'Colors.indigo.shade100': Colors.indigo.shade100,
  'Colors.indigo.shade200': Colors.indigo.shade200,
  'Colors.indigo.shade300': Colors.indigo.shade300,
  'Colors.indigo.shade400': Colors.indigo.shade400,
  'Colors.indigo.shade500': Colors.indigo.shade500,
  'Colors.indigo.shade600': Colors.indigo.shade600,
  'Colors.indigo.shade700': Colors.indigo.shade700,
  'Colors.indigo.shade800': Colors.indigo.shade800,
  'Colors.indigo.shade900': Colors.indigo.shade900,
  'Colors.indigoAccent': Colors.indigoAccent,
  'Colors.indigoAccent.shade100': Colors.indigoAccent.shade100,
  'Colors.indigoAccent.shade200': Colors.indigoAccent.shade200,
  'Colors.indigoAccent.shade400': Colors.indigoAccent.shade400,
  'Colors.indigoAccent.shade700': Colors.indigoAccent.shade700,
  'Colors.blue': Colors.blue,
  'Colors.blue.shade50': Colors.blue.shade50,
  'Colors.blue.shade100': Colors.blue.shade100,
  'Colors.blue.shade200': Colors.blue.shade200,
  'Colors.blue.shade300': Colors.blue.shade300,
  'Colors.blue.shade400': Colors.blue.shade400,
  'Colors.blue.shade500': Colors.blue.shade500,
  'Colors.blue.shade600': Colors.blue.shade600,
  'Colors.blue.shade700': Colors.blue.shade700,
  'Colors.blue.shade800': Colors.blue.shade800,
  'Colors.blue.shade900': Colors.blue.shade900,
  'Colors.blueAccent': Colors.blueAccent,
  'Colors.blueAccent.shade100': Colors.blueAccent.shade100,
  'Colors.blueAccent.shade200': Colors.blueAccent.shade200,
  'Colors.blueAccent.shade400': Colors.blueAccent.shade400,
  'Colors.blueAccent.shade700': Colors.blueAccent.shade700,
  'Colors.lightBlue': Colors.lightBlue,
  'Colors.lightBlue.shade50': Colors.lightBlue.shade50,
  'Colors.lightBlue.shade100': Colors.lightBlue.shade100,
  'Colors.lightBlue.shade200': Colors.lightBlue.shade200,
  'Colors.lightBlue.shade300': Colors.lightBlue.shade300,
  'Colors.lightBlue.shade400': Colors.lightBlue.shade400,
  'Colors.lightBlue.shade500': Colors.lightBlue.shade500,
  'Colors.lightBlue.shade600': Colors.lightBlue.shade600,
  'Colors.lightBlue.shade700': Colors.lightBlue.shade700,
  'Colors.lightBlue.shade800': Colors.lightBlue.shade800,
  'Colors.lightBlue.shade900': Colors.lightBlue.shade900,
  'Colors.lightBlueAccent': Colors.lightBlueAccent,
  'Colors.lightBlueAccent.shade100': Colors.lightBlueAccent.shade100,
  'Colors.lightBlueAccent.shade200': Colors.lightBlueAccent.shade200,
  'Colors.lightBlueAccent.shade400': Colors.lightBlueAccent.shade400,
  'Colors.lightBlueAccent.shade700': Colors.lightBlueAccent.shade700,
  'Colors.cyan': Colors.cyan,
  'Colors.cyan.shade50': Colors.cyan.shade50,
  'Colors.cyan.shade100': Colors.cyan.shade100,
  'Colors.cyan.shade200': Colors.cyan.shade200,
  'Colors.cyan.shade300': Colors.cyan.shade300,
  'Colors.cyan.shade400': Colors.cyan.shade400,
  'Colors.cyan.shade500': Colors.cyan.shade500,
  'Colors.cyan.shade600': Colors.cyan.shade600,
  'Colors.cyan.shade700': Colors.cyan.shade700,
  'Colors.cyan.shade800': Colors.cyan.shade800,
  'Colors.cyan.shade900': Colors.cyan.shade900,
  'Colors.cyanAccent': Colors.cyanAccent,
  'Colors.cyanAccent.shade100': Colors.cyanAccent.shade100,
  'Colors.cyanAccent.shade200': Colors.cyanAccent.shade200,
  'Colors.cyanAccent.shade400': Colors.cyanAccent.shade400,
  'Colors.cyanAccent.shade700': Colors.cyanAccent.shade700,
  'Colors.teal': Colors.teal,
  'Colors.teal.shade50': Colors.teal.shade50,
  'Colors.teal.shade100': Colors.teal.shade100,
  'Colors.teal.shade200': Colors.teal.shade200,
  'Colors.teal.shade300': Colors.teal.shade300,
  'Colors.teal.shade400': Colors.teal.shade400,
  'Colors.teal.shade500': Colors.teal.shade500,
  'Colors.teal.shade600': Colors.teal.shade600,
  'Colors.teal.shade700': Colors.teal.shade700,
  'Colors.teal.shade800': Colors.teal.shade800,
  'Colors.teal.shade900': Colors.teal.shade900,
  'Colors.tealAccent': Colors.tealAccent,
  'Colors.tealAccent.shade100': Colors.tealAccent.shade100,
  'Colors.tealAccent.shade200': Colors.tealAccent.shade200,
  'Colors.tealAccent.shade400': Colors.tealAccent.shade400,
  'Colors.tealAccent.shade700': Colors.tealAccent.shade700,
  'Colors.green': Colors.green,
  'Colors.green.shade50': Colors.green.shade50,
  'Colors.green.shade100': Colors.green.shade100,
  'Colors.green.shade200': Colors.green.shade200,
  'Colors.green.shade300': Colors.green.shade300,
  'Colors.green.shade400': Colors.green.shade400,
  'Colors.green.shade500': Colors.green.shade500,
  'Colors.green.shade600': Colors.green.shade600,
  'Colors.green.shade700': Colors.green.shade700,
  'Colors.green.shade800': Colors.green.shade800,
  'Colors.green.shade900': Colors.green.shade900,
  'Colors.greenAccent': Colors.greenAccent,
  'Colors.greenAccent.shade100': Colors.greenAccent.shade100,
  'Colors.greenAccent.shade200': Colors.greenAccent.shade200,
  'Colors.greenAccent.shade400': Colors.greenAccent.shade400,
  'Colors.greenAccent.shade700': Colors.greenAccent.shade700,
  'Colors.lightGreen': Colors.lightGreen,
  'Colors.lightGreen.shade50': Colors.lightGreen.shade50,
  'Colors.lightGreen.shade100': Colors.lightGreen.shade100,
  'Colors.lightGreen.shade200': Colors.lightGreen.shade200,
  'Colors.lightGreen.shade300': Colors.lightGreen.shade300,
  'Colors.lightGreen.shade400': Colors.lightGreen.shade400,
  'Colors.lightGreen.shade500': Colors.lightGreen.shade500,
  'Colors.lightGreen.shade600': Colors.lightGreen.shade600,
  'Colors.lightGreen.shade700': Colors.lightGreen.shade700,
  'Colors.lightGreen.shade800': Colors.lightGreen.shade800,
  'Colors.lightGreen.shade900': Colors.lightGreen.shade900,
  'Colors.lightGreenAccent': Colors.lightGreenAccent,
  'Colors.lightGreenAccent.shade100': Colors.lightGreenAccent.shade100,
  'Colors.lightGreenAccent.shade200': Colors.lightGreenAccent.shade200,
  'Colors.lightGreenAccent.shade400': Colors.lightGreenAccent.shade400,
  'Colors.lightGreenAccent.shade700': Colors.lightGreenAccent.shade700,
  'Colors.lime': Colors.lime,
  'Colors.lime.shade50': Colors.lime.shade50,
  'Colors.lime.shade100': Colors.lime.shade100,
  'Colors.lime.shade200': Colors.lime.shade200,
  'Colors.lime.shade300': Colors.lime.shade300,
  'Colors.lime.shade400': Colors.lime.shade400,
  'Colors.lime.shade500': Colors.lime.shade500,
  'Colors.lime.shade600': Colors.lime.shade600,
  'Colors.lime.shade700': Colors.lime.shade700,
  'Colors.lime.shade800': Colors.lime.shade800,
  'Colors.lime.shade900': Colors.lime.shade900,
  'Colors.limeAccent': Colors.limeAccent,
  'Colors.limeAccent.shade100': Colors.limeAccent.shade100,
  'Colors.limeAccent.shade200': Colors.limeAccent.shade200,
  'Colors.limeAccent.shade400': Colors.limeAccent.shade400,
  'Colors.limeAccent.shade700': Colors.limeAccent.shade700,
  'Colors.yellow': Colors.yellow,
  'Colors.yellow.shade50': Colors.yellow.shade50,
  'Colors.yellow.shade100': Colors.yellow.shade100,
  'Colors.yellow.shade200': Colors.yellow.shade200,
  'Colors.yellow.shade300': Colors.yellow.shade300,
  'Colors.yellow.shade400': Colors.yellow.shade400,
  'Colors.yellow.shade500': Colors.yellow.shade500,
  'Colors.yellow.shade600': Colors.yellow.shade600,
  'Colors.yellow.shade700': Colors.yellow.shade700,
  'Colors.yellow.shade800': Colors.yellow.shade800,
  'Colors.yellow.shade900': Colors.yellow.shade900,
  'Colors.yellowAccent': Colors.yellowAccent,
  'Colors.yellowAccent.shade100': Colors.yellowAccent.shade100,
  'Colors.yellowAccent.shade200': Colors.yellowAccent.shade200,
  'Colors.yellowAccent.shade400': Colors.yellowAccent.shade400,
  'Colors.yellowAccent.shade700': Colors.yellowAccent.shade700,
  'Colors.amber': Colors.amber,
  'Colors.amber.shade50': Colors.amber.shade50,
  'Colors.amber.shade100': Colors.amber.shade100,
  'Colors.amber.shade200': Colors.amber.shade200,
  'Colors.amber.shade300': Colors.amber.shade300,
  'Colors.amber.shade400': Colors.amber.shade400,
  'Colors.amber.shade500': Colors.amber.shade500,
  'Colors.amber.shade600': Colors.amber.shade600,
  'Colors.amber.shade700': Colors.amber.shade700,
  'Colors.amber.shade800': Colors.amber.shade800,
  'Colors.amber.shade900': Colors.amber.shade900,
  'Colors.amberAccent': Colors.amberAccent,
  'Colors.amberAccent.shade100': Colors.amberAccent.shade100,
  'Colors.amberAccent.shade200': Colors.amberAccent.shade200,
  'Colors.amberAccent.shade400': Colors.amberAccent.shade400,
  'Colors.amberAccent.shade700': Colors.amberAccent.shade700,
  'Colors.orange': Colors.orange,
  'Colors.orange.shade50': Colors.orange.shade50,
  'Colors.orange.shade100': Colors.orange.shade100,
  'Colors.orange.shade200': Colors.orange.shade200,
  'Colors.orange.shade300': Colors.orange.shade300,
  'Colors.orange.shade400': Colors.orange.shade400,
  'Colors.orange.shade500': Colors.orange.shade500,
  'Colors.orange.shade600': Colors.orange.shade600,
  'Colors.orange.shade700': Colors.orange.shade700,
  'Colors.orange.shade800': Colors.orange.shade800,
  'Colors.orange.shade900': Colors.orange.shade900,
  'Colors.orangeAccent': Colors.orangeAccent,
  'Colors.orangeAccent.shade100': Colors.orangeAccent.shade100,
  'Colors.orangeAccent.shade200': Colors.orangeAccent.shade200,
  'Colors.orangeAccent.shade400': Colors.orangeAccent.shade400,
  'Colors.orangeAccent.shade700': Colors.orangeAccent.shade700,
  'Colors.deepOrange': Colors.deepOrange,
  'Colors.deepOrange.shade50': Colors.deepOrange.shade50,
  'Colors.deepOrange.shade100': Colors.deepOrange.shade100,
  'Colors.deepOrange.shade200': Colors.deepOrange.shade200,
  'Colors.deepOrange.shade300': Colors.deepOrange.shade300,
  'Colors.deepOrange.shade400': Colors.deepOrange.shade400,
  'Colors.deepOrange.shade500': Colors.deepOrange.shade500,
  'Colors.deepOrange.shade600': Colors.deepOrange.shade600,
  'Colors.deepOrange.shade700': Colors.deepOrange.shade700,
  'Colors.deepOrange.shade800': Colors.deepOrange.shade800,
  'Colors.deepOrange.shade900': Colors.deepOrange.shade900,
  'Colors.deepOrangeAccent': Colors.deepOrangeAccent,
  'Colors.deepOrangeAccent.shade100': Colors.deepOrangeAccent.shade100,
  'Colors.deepOrangeAccent.shade200': Colors.deepOrangeAccent.shade200,
  'Colors.deepOrangeAccent.shade400': Colors.deepOrangeAccent.shade400,
  'Colors.deepOrangeAccent.shade700': Colors.deepOrangeAccent.shade700,
  'Colors.brown': Colors.brown,
  'Colors.brown.shade50': Colors.brown.shade50,
  'Colors.brown.shade100': Colors.brown.shade100,
  'Colors.brown.shade200': Colors.brown.shade200,
  'Colors.brown.shade300': Colors.brown.shade300,
  'Colors.brown.shade400': Colors.brown.shade400,
  'Colors.brown.shade500': Colors.brown.shade500,
  'Colors.brown.shade600': Colors.brown.shade600,
  'Colors.brown.shade700': Colors.brown.shade700,
  'Colors.brown.shade800': Colors.brown.shade800,
  'Colors.brown.shade900': Colors.brown.shade900,
  'Colors.grey': Colors.grey,
  'Colors.grey.shade50': Colors.grey.shade50,
  'Colors.grey.shade100': Colors.grey.shade100,
  'Colors.grey.shade200': Colors.grey.shade200,
  'Colors.grey.shade300': Colors.grey.shade300,
  'Colors.grey.shade400': Colors.grey.shade400,
  'Colors.grey.shade500': Colors.grey.shade500,
  'Colors.grey.shade600': Colors.grey.shade600,
  'Colors.grey.shade700': Colors.grey.shade700,
  'Colors.grey.shade800': Colors.grey.shade800,
  'Colors.grey.shade900': Colors.grey.shade900,
  'Colors.blueGrey': Colors.blueGrey,
  'Colors.blueGrey.shade50': Colors.blueGrey.shade50,
  'Colors.blueGrey.shade100': Colors.blueGrey.shade100,
  'Colors.blueGrey.shade200': Colors.blueGrey.shade200,
  'Colors.blueGrey.shade300': Colors.blueGrey.shade300,
  'Colors.blueGrey.shade400': Colors.blueGrey.shade400,
  'Colors.blueGrey.shade500': Colors.blueGrey.shade500,
  'Colors.blueGrey.shade600': Colors.blueGrey.shade600,
  'Colors.blueGrey.shade700': Colors.blueGrey.shade700,
  'Colors.blueGrey.shade800': Colors.blueGrey.shade800,
  'Colors.blueGrey.shade900': Colors.blueGrey.shade900,
  'Colors.white': Colors.white,
  'Colors.white10': Colors.white10,
  'Colors.white12': Colors.white12,
  'Colors.white24': Colors.white24,
  'Colors.white30': Colors.white30,
  'Colors.white38': Colors.white38,
  'Colors.white54': Colors.white54,
  'Colors.white60': Colors.white60,
  'Colors.white70': Colors.white70,
  'Colors.black': Colors.black,
  'Colors.black12': Colors.black12,
  'Colors.black26': Colors.black26,
  'Colors.black38': Colors.black38,
  'Colors.black45': Colors.black45,
  'Colors.black54': Colors.black54,
  'Colors.black87': Colors.black87,
});

dynamic _buildValue(String source, Map<String, SourceNode> children) =>
  source == 'ThemeData' ? ThemeData(
    colorScheme: children['?#colorScheme']!.value,
    brightness: children['?#brightness']!.value,
    primarySwatch: children['?#primarySwatch']!.value,
    primaryColor: children['?#primaryColor']!.value,
    primaryColorLight: children['?#primaryColorLight']!.value,
    primaryColorDark: children['?#primaryColorDark']!.value,
    primaryColorBrightness: children['?#primaryColorBrightness']!.value,
    accentColor: children['?#accentColor']!.value,
    accentColorBrightness: children['?#accentColorBrightness']!.value,
    elevatedButtonTheme: children['?#elevatedButtonTheme']!.value,
    outlinedButtonTheme: children['?#outlinedButtonTheme']!.value,
    textButtonTheme: children['?#textButtonTheme']!.value,
  ) :
  source == 'ColorScheme.fromSwatch' ? ColorScheme.fromSwatch(
    primarySwatch: children['@!#primarySwatch']!.value ?? Colors.blue,
    primaryColorDark: children['?#primaryColorDark']!.value,
    accentColor: children['?#accentColor']!.value,
    cardColor: children['?#cardColor']!.value,
    backgroundColor: children['?#backgroundColor']!.value,
    errorColor: children['?#errorColor']!.value,
    brightness: children['@!#brightness']!.value ?? Brightness.light,
  ) :
  source == 'ColorScheme.light' ? ColorScheme.light(
    primary: children['@!#primary']!.value ?? Color(0xff6200ee),
    primaryVariant: children['@!#primaryVariant']!.value ?? Color(0xff3700b3),
    secondary: children['@!#secondary']!.value ?? Color(0xff03dac6),
    secondaryVariant: children['@!#secondaryVariant']!.value ?? Color(0xff018786),
    surface: children['@!#surface']!.value ?? Colors.white,
    background: children['@!#background']!.value ?? Colors.white,
    error: children['@!#error']!.value ?? Color(0xffb00020),
    onPrimary: children['@!#onPrimary']!.value ?? Colors.white,
    onSecondary: children['@!#onSecondary']!.value ?? Colors.black,
    onSurface: children['@!#onSurface']!.value ?? Colors.black,
    onBackground: children['@!#onBackground']!.value ?? Colors.black,
    onError: children['@!#onError']!.value ?? Colors.white,
    brightness: children['@!#brightness']!.value ?? Brightness.light,
  ) :
  source == 'ColorScheme.dark' ? ColorScheme.dark(
    primary: children['@!#primary']!.value ?? Color(0xffbb86fc),
    primaryVariant: children['@!#primaryVariant']!.value ?? Color(0xff3700B3),
    secondary: children['@!#secondary']!.value ?? Color(0xff03dac6),
    secondaryVariant: children['@!#secondaryVariant']!.value ?? Color(0xff03dac6),
    surface: children['@!#surface']!.value ?? Color(0xff121212),
    background: children['@!#background']!.value ?? Color(0xff121212),
    error: children['@!#error']!.value ?? Color(0xffcf6679),
    onPrimary: children['@!#onPrimary']!.value ?? Colors.black,
    onSecondary: children['@!#onSecondary']!.value ?? Colors.black,
    onSurface: children['@!#onSurface']!.value ?? Colors.white,
    onBackground: children['@!#onBackground']!.value ?? Colors.white,
    onError: children['@!#onError']!.value ?? Colors.black,
    brightness: children['@!#brightness']!.value ?? Brightness.dark,
  ) :
  source == 'ElevatedButtonThemeData' ? ElevatedButtonThemeData(
    style: children['?#style']!.value,
  ) :
  source == 'OutlinedButtonThemeData' ? OutlinedButtonThemeData(
    style: children['?#style']!.value,
  ) :
  source == 'TextButtonThemeData' ? TextButtonThemeData(
    style: children['?#style']!.value,
  ) :
  source == 'ElevatedButton.styleFrom' ? ElevatedButton.styleFrom(
    primary: children['?#primary']!.value,
    onPrimary: children['?#onPrimary']!.value,
    onSurface: children['?#onSurface']!.value,
  ) :
  source == 'OutlinedButton.styleFrom' ? OutlinedButton.styleFrom(
    primary: children['?#primary']!.value,
    onSurface: children['?#onSurface']!.value,
  ) :
  source == 'TextButton.styleFrom' ? TextButton.styleFrom(
    primary: children['?#primary']!.value,
    onSurface: children['?#onSurface']!.value,
  ) :
  throw('unsupported: source=$source children=$children');
