// todo: generate this file automatically.

part of 'source_node.dart';

final Iterable<SourceNode<Brightness>> brightnessOptions = [
  SourceNode('Brightness.dark'),
  SourceNode('Brightness.light'),
];

final Iterable<SourceNode<Color>> colorsOptions = [
  SourceNode('Colors.red'),
  SourceNode('Colors.red.shade50'),
  SourceNode('Colors.red.shade100'),
  SourceNode('Colors.red.shade200'),
  SourceNode('Colors.red.shade300'),
  SourceNode('Colors.red.shade400'),
  SourceNode('Colors.red.shade500'),
  SourceNode('Colors.red.shade600'),
  SourceNode('Colors.red.shade700'),
  SourceNode('Colors.red.shade800'),
  SourceNode('Colors.red.shade900'),
  SourceNode('Colors.redAccent'),
  SourceNode('Colors.redAccent.shade100'),
  SourceNode('Colors.redAccent.shade200'),
  SourceNode('Colors.redAccent.shade400'),
  SourceNode('Colors.redAccent.shade700'),
  SourceNode('Colors.pink'),
  SourceNode('Colors.pink.shade50'),
  SourceNode('Colors.pink.shade100'),
  SourceNode('Colors.pink.shade200'),
  SourceNode('Colors.pink.shade300'),
  SourceNode('Colors.pink.shade400'),
  SourceNode('Colors.pink.shade500'),
  SourceNode('Colors.pink.shade600'),
  SourceNode('Colors.pink.shade700'),
  SourceNode('Colors.pink.shade800'),
  SourceNode('Colors.pink.shade900'),
  SourceNode('Colors.pinkAccent'),
  SourceNode('Colors.pinkAccent.shade100'),
  SourceNode('Colors.pinkAccent.shade200'),
  SourceNode('Colors.pinkAccent.shade400'),
  SourceNode('Colors.pinkAccent.shade700'),
  SourceNode('Colors.purple'),
  SourceNode('Colors.purple.shade50'),
  SourceNode('Colors.purple.shade100'),
  SourceNode('Colors.purple.shade200'),
  SourceNode('Colors.purple.shade300'),
  SourceNode('Colors.purple.shade400'),
  SourceNode('Colors.purple.shade500'),
  SourceNode('Colors.purple.shade600'),
  SourceNode('Colors.purple.shade700'),
  SourceNode('Colors.purple.shade800'),
  SourceNode('Colors.purple.shade900'),
  SourceNode('Colors.purpleAccent'),
  SourceNode('Colors.purpleAccent.shade100'),
  SourceNode('Colors.purpleAccent.shade200'),
  SourceNode('Colors.purpleAccent.shade400'),
  SourceNode('Colors.purpleAccent.shade700'),
  SourceNode('Colors.deepPurple'),
  SourceNode('Colors.deepPurple.shade50'),
  SourceNode('Colors.deepPurple.shade100'),
  SourceNode('Colors.deepPurple.shade200'),
  SourceNode('Colors.deepPurple.shade300'),
  SourceNode('Colors.deepPurple.shade400'),
  SourceNode('Colors.deepPurple.shade500'),
  SourceNode('Colors.deepPurple.shade600'),
  SourceNode('Colors.deepPurple.shade700'),
  SourceNode('Colors.deepPurple.shade800'),
  SourceNode('Colors.deepPurple.shade900'),
  SourceNode('Colors.deepPurpleAccent'),
  SourceNode('Colors.deepPurpleAccent.shade100'),
  SourceNode('Colors.deepPurpleAccent.shade200'),
  SourceNode('Colors.deepPurpleAccent.shade400'),
  SourceNode('Colors.deepPurpleAccent.shade700'),
  SourceNode('Colors.indigo'),
  SourceNode('Colors.indigo.shade50'),
  SourceNode('Colors.indigo.shade100'),
  SourceNode('Colors.indigo.shade200'),
  SourceNode('Colors.indigo.shade300'),
  SourceNode('Colors.indigo.shade400'),
  SourceNode('Colors.indigo.shade500'),
  SourceNode('Colors.indigo.shade600'),
  SourceNode('Colors.indigo.shade700'),
  SourceNode('Colors.indigo.shade800'),
  SourceNode('Colors.indigo.shade900'),
  SourceNode('Colors.indigoAccent'),
  SourceNode('Colors.indigoAccent.shade100'),
  SourceNode('Colors.indigoAccent.shade200'),
  SourceNode('Colors.indigoAccent.shade400'),
  SourceNode('Colors.indigoAccent.shade700'),
  SourceNode('Colors.blue'),
  SourceNode('Colors.blue.shade50'),
  SourceNode('Colors.blue.shade100'),
  SourceNode('Colors.blue.shade200'),
  SourceNode('Colors.blue.shade300'),
  SourceNode('Colors.blue.shade400'),
  SourceNode('Colors.blue.shade500'),
  SourceNode('Colors.blue.shade600'),
  SourceNode('Colors.blue.shade700'),
  SourceNode('Colors.blue.shade800'),
  SourceNode('Colors.blue.shade900'),
  SourceNode('Colors.blueAccent'),
  SourceNode('Colors.blueAccent.shade100'),
  SourceNode('Colors.blueAccent.shade200'),
  SourceNode('Colors.blueAccent.shade400'),
  SourceNode('Colors.blueAccent.shade700'),
  SourceNode('Colors.lightBlue'),
  SourceNode('Colors.lightBlue.shade50'),
  SourceNode('Colors.lightBlue.shade100'),
  SourceNode('Colors.lightBlue.shade200'),
  SourceNode('Colors.lightBlue.shade300'),
  SourceNode('Colors.lightBlue.shade400'),
  SourceNode('Colors.lightBlue.shade500'),
  SourceNode('Colors.lightBlue.shade600'),
  SourceNode('Colors.lightBlue.shade700'),
  SourceNode('Colors.lightBlue.shade800'),
  SourceNode('Colors.lightBlue.shade900'),
  SourceNode('Colors.lightBlueAccent'),
  SourceNode('Colors.lightBlueAccent.shade100'),
  SourceNode('Colors.lightBlueAccent.shade200'),
  SourceNode('Colors.lightBlueAccent.shade400'),
  SourceNode('Colors.lightBlueAccent.shade700'),
  SourceNode('Colors.cyan'),
  SourceNode('Colors.cyan.shade50'),
  SourceNode('Colors.cyan.shade100'),
  SourceNode('Colors.cyan.shade200'),
  SourceNode('Colors.cyan.shade300'),
  SourceNode('Colors.cyan.shade400'),
  SourceNode('Colors.cyan.shade500'),
  SourceNode('Colors.cyan.shade600'),
  SourceNode('Colors.cyan.shade700'),
  SourceNode('Colors.cyan.shade800'),
  SourceNode('Colors.cyan.shade900'),
  SourceNode('Colors.cyanAccent'),
  SourceNode('Colors.cyanAccent.shade100'),
  SourceNode('Colors.cyanAccent.shade200'),
  SourceNode('Colors.cyanAccent.shade400'),
  SourceNode('Colors.cyanAccent.shade700'),
  SourceNode('Colors.teal'),
  SourceNode('Colors.teal.shade50'),
  SourceNode('Colors.teal.shade100'),
  SourceNode('Colors.teal.shade200'),
  SourceNode('Colors.teal.shade300'),
  SourceNode('Colors.teal.shade400'),
  SourceNode('Colors.teal.shade500'),
  SourceNode('Colors.teal.shade600'),
  SourceNode('Colors.teal.shade700'),
  SourceNode('Colors.teal.shade800'),
  SourceNode('Colors.teal.shade900'),
  SourceNode('Colors.tealAccent'),
  SourceNode('Colors.tealAccent.shade100'),
  SourceNode('Colors.tealAccent.shade200'),
  SourceNode('Colors.tealAccent.shade400'),
  SourceNode('Colors.tealAccent.shade700'),
  SourceNode('Colors.green'),
  SourceNode('Colors.green.shade50'),
  SourceNode('Colors.green.shade100'),
  SourceNode('Colors.green.shade200'),
  SourceNode('Colors.green.shade300'),
  SourceNode('Colors.green.shade400'),
  SourceNode('Colors.green.shade500'),
  SourceNode('Colors.green.shade600'),
  SourceNode('Colors.green.shade700'),
  SourceNode('Colors.green.shade800'),
  SourceNode('Colors.green.shade900'),
  SourceNode('Colors.greenAccent'),
  SourceNode('Colors.greenAccent.shade100'),
  SourceNode('Colors.greenAccent.shade200'),
  SourceNode('Colors.greenAccent.shade400'),
  SourceNode('Colors.greenAccent.shade700'),
  SourceNode('Colors.lightGreen'),
  SourceNode('Colors.lightGreen.shade50'),
  SourceNode('Colors.lightGreen.shade100'),
  SourceNode('Colors.lightGreen.shade200'),
  SourceNode('Colors.lightGreen.shade300'),
  SourceNode('Colors.lightGreen.shade400'),
  SourceNode('Colors.lightGreen.shade500'),
  SourceNode('Colors.lightGreen.shade600'),
  SourceNode('Colors.lightGreen.shade700'),
  SourceNode('Colors.lightGreen.shade800'),
  SourceNode('Colors.lightGreen.shade900'),
  SourceNode('Colors.lightGreenAccent'),
  SourceNode('Colors.lightGreenAccent.shade100'),
  SourceNode('Colors.lightGreenAccent.shade200'),
  SourceNode('Colors.lightGreenAccent.shade400'),
  SourceNode('Colors.lightGreenAccent.shade700'),
  SourceNode('Colors.lime'),
  SourceNode('Colors.lime.shade50'),
  SourceNode('Colors.lime.shade100'),
  SourceNode('Colors.lime.shade200'),
  SourceNode('Colors.lime.shade300'),
  SourceNode('Colors.lime.shade400'),
  SourceNode('Colors.lime.shade500'),
  SourceNode('Colors.lime.shade600'),
  SourceNode('Colors.lime.shade700'),
  SourceNode('Colors.lime.shade800'),
  SourceNode('Colors.lime.shade900'),
  SourceNode('Colors.limeAccent'),
  SourceNode('Colors.limeAccent.shade100'),
  SourceNode('Colors.limeAccent.shade200'),
  SourceNode('Colors.limeAccent.shade400'),
  SourceNode('Colors.limeAccent.shade700'),
  SourceNode('Colors.yellow'),
  SourceNode('Colors.yellow.shade50'),
  SourceNode('Colors.yellow.shade100'),
  SourceNode('Colors.yellow.shade200'),
  SourceNode('Colors.yellow.shade300'),
  SourceNode('Colors.yellow.shade400'),
  SourceNode('Colors.yellow.shade500'),
  SourceNode('Colors.yellow.shade600'),
  SourceNode('Colors.yellow.shade700'),
  SourceNode('Colors.yellow.shade800'),
  SourceNode('Colors.yellow.shade900'),
  SourceNode('Colors.yellowAccent'),
  SourceNode('Colors.yellowAccent.shade100'),
  SourceNode('Colors.yellowAccent.shade200'),
  SourceNode('Colors.yellowAccent.shade400'),
  SourceNode('Colors.yellowAccent.shade700'),
  SourceNode('Colors.amber'),
  SourceNode('Colors.amber.shade50'),
  SourceNode('Colors.amber.shade100'),
  SourceNode('Colors.amber.shade200'),
  SourceNode('Colors.amber.shade300'),
  SourceNode('Colors.amber.shade400'),
  SourceNode('Colors.amber.shade500'),
  SourceNode('Colors.amber.shade600'),
  SourceNode('Colors.amber.shade700'),
  SourceNode('Colors.amber.shade800'),
  SourceNode('Colors.amber.shade900'),
  SourceNode('Colors.amberAccent'),
  SourceNode('Colors.amberAccent.shade100'),
  SourceNode('Colors.amberAccent.shade200'),
  SourceNode('Colors.amberAccent.shade400'),
  SourceNode('Colors.amberAccent.shade700'),
  SourceNode('Colors.orange'),
  SourceNode('Colors.orange.shade50'),
  SourceNode('Colors.orange.shade100'),
  SourceNode('Colors.orange.shade200'),
  SourceNode('Colors.orange.shade300'),
  SourceNode('Colors.orange.shade400'),
  SourceNode('Colors.orange.shade500'),
  SourceNode('Colors.orange.shade600'),
  SourceNode('Colors.orange.shade700'),
  SourceNode('Colors.orange.shade800'),
  SourceNode('Colors.orange.shade900'),
  SourceNode('Colors.orangeAccent'),
  SourceNode('Colors.orangeAccent.shade100'),
  SourceNode('Colors.orangeAccent.shade200'),
  SourceNode('Colors.orangeAccent.shade400'),
  SourceNode('Colors.orangeAccent.shade700'),
  SourceNode('Colors.deepOrange'),
  SourceNode('Colors.deepOrange.shade50'),
  SourceNode('Colors.deepOrange.shade100'),
  SourceNode('Colors.deepOrange.shade200'),
  SourceNode('Colors.deepOrange.shade300'),
  SourceNode('Colors.deepOrange.shade400'),
  SourceNode('Colors.deepOrange.shade500'),
  SourceNode('Colors.deepOrange.shade600'),
  SourceNode('Colors.deepOrange.shade700'),
  SourceNode('Colors.deepOrange.shade800'),
  SourceNode('Colors.deepOrange.shade900'),
  SourceNode('Colors.deepOrangeAccent'),
  SourceNode('Colors.deepOrangeAccent.shade100'),
  SourceNode('Colors.deepOrangeAccent.shade200'),
  SourceNode('Colors.deepOrangeAccent.shade400'),
  SourceNode('Colors.deepOrangeAccent.shade700'),
  SourceNode('Colors.brown'),
  SourceNode('Colors.brown.shade50'),
  SourceNode('Colors.brown.shade100'),
  SourceNode('Colors.brown.shade200'),
  SourceNode('Colors.brown.shade300'),
  SourceNode('Colors.brown.shade400'),
  SourceNode('Colors.brown.shade500'),
  SourceNode('Colors.brown.shade600'),
  SourceNode('Colors.brown.shade700'),
  SourceNode('Colors.brown.shade800'),
  SourceNode('Colors.brown.shade900'),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode('Colors.grey'),
  SourceNode('Colors.grey.shade50'),
  SourceNode('Colors.grey.shade100'),
  SourceNode('Colors.grey.shade200'),
  SourceNode('Colors.grey.shade300'),
  SourceNode('Colors.grey.shade400'),
  SourceNode('Colors.grey.shade500'),
  SourceNode('Colors.grey.shade600'),
  SourceNode('Colors.grey.shade700'),
  SourceNode('Colors.grey.shade800'),
  SourceNode('Colors.grey.shade900'),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode('Colors.blueGrey'),
  SourceNode('Colors.blueGrey.shade50'),
  SourceNode('Colors.blueGrey.shade100'),
  SourceNode('Colors.blueGrey.shade200'),
  SourceNode('Colors.blueGrey.shade300'),
  SourceNode('Colors.blueGrey.shade400'),
  SourceNode('Colors.blueGrey.shade500'),
  SourceNode('Colors.blueGrey.shade600'),
  SourceNode('Colors.blueGrey.shade700'),
  SourceNode('Colors.blueGrey.shade800'),
  SourceNode('Colors.blueGrey.shade900'),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode('Colors.white'),
  SourceNode('Colors.white10'),
  SourceNode('Colors.white12'),
  SourceNode('Colors.white24'),
  SourceNode('Colors.white30'),
  SourceNode('Colors.white38'),
  SourceNode('Colors.white54'),
  SourceNode('Colors.white60'),
  SourceNode('Colors.white70'),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode('Colors.black'),
  SourceNode('Colors.black12'),
  SourceNode('Colors.black26'),
  SourceNode('Colors.black38'),
  SourceNode('Colors.black45'),
  SourceNode('Colors.black54'),
  SourceNode('Colors.black87'),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
  SourceNode(),
];

final Iterable<SourceNode<MaterialColor>> colorsMaterialOptions = [
  SourceNode('Colors.red'),
  SourceNode('Colors.pink'),
  SourceNode('Colors.purple'),
  SourceNode('Colors.deepPurple'),
  SourceNode('Colors.indigo'),
  SourceNode('Colors.blue'),
  SourceNode('Colors.lightBlue'),
  SourceNode('Colors.cyan'),
  SourceNode('Colors.teal'),
  SourceNode('Colors.green'),
  SourceNode('Colors.lightGreen'),
  SourceNode('Colors.lime'),
  SourceNode('Colors.yellow'),
  SourceNode('Colors.amber'),
  SourceNode('Colors.orange'),
  SourceNode('Colors.deepOrange'),
  SourceNode('Colors.brown'),
  SourceNode('Colors.grey'),
  SourceNode('Colors.blueGrey'),
];

final Map<String, dynamic> _sourceValues = Map.unmodifiable(<String, dynamic>{
  'Brightness.dark': Brightness.dark,
  'Brightness.light': Brightness.light,
  'Colors.red': Colors.red,
  'Colors.red.shade50': Colors.red.shade50,
  'Colors.red.shade100': Colors.red.shade100,
  'Colors.red.shade200': Colors.red.shade200,
  'Colors.red.shade300': Colors.red.shade300,
  'Colors.red.shade400': Colors.red.shade400,
  'Colors.red.shade500': Colors.red.shade500,
  'Colors.red.shade600': Colors.red.shade600,
  'Colors.red.shade700': Colors.red.shade700,
  'Colors.red.shade800': Colors.red.shade800,
  'Colors.red.shade900': Colors.red.shade900,
  'Colors.redAccent': Colors.redAccent,
  'Colors.redAccent.shade100': Colors.redAccent.shade100,
  'Colors.redAccent.shade200': Colors.redAccent.shade200,
  'Colors.redAccent.shade400': Colors.redAccent.shade400,
  'Colors.redAccent.shade700': Colors.redAccent.shade700,
  'Colors.pink': Colors.pink,
  'Colors.pink.shade50': Colors.pink.shade50,
  'Colors.pink.shade100': Colors.pink.shade100,
  'Colors.pink.shade200': Colors.pink.shade200,
  'Colors.pink.shade300': Colors.pink.shade300,
  'Colors.pink.shade400': Colors.pink.shade400,
  'Colors.pink.shade500': Colors.pink.shade500,
  'Colors.pink.shade600': Colors.pink.shade600,
  'Colors.pink.shade700': Colors.pink.shade700,
  'Colors.pink.shade800': Colors.pink.shade800,
  'Colors.pink.shade900': Colors.pink.shade900,
  'Colors.pinkAccent': Colors.pinkAccent,
  'Colors.pinkAccent.shade100': Colors.pinkAccent.shade100,
  'Colors.pinkAccent.shade200': Colors.pinkAccent.shade200,
  'Colors.pinkAccent.shade400': Colors.pinkAccent.shade400,
  'Colors.pinkAccent.shade700': Colors.pinkAccent.shade700,
  'Colors.purple': Colors.purple,
  'Colors.purple.shade50': Colors.purple.shade50,
  'Colors.purple.shade100': Colors.purple.shade100,
  'Colors.purple.shade200': Colors.purple.shade200,
  'Colors.purple.shade300': Colors.purple.shade300,
  'Colors.purple.shade400': Colors.purple.shade400,
  'Colors.purple.shade500': Colors.purple.shade500,
  'Colors.purple.shade600': Colors.purple.shade600,
  'Colors.purple.shade700': Colors.purple.shade700,
  'Colors.purple.shade800': Colors.purple.shade800,
  'Colors.purple.shade900': Colors.purple.shade900,
  'Colors.purpleAccent': Colors.purpleAccent,
  'Colors.purpleAccent.shade100': Colors.purpleAccent.shade100,
  'Colors.purpleAccent.shade200': Colors.purpleAccent.shade200,
  'Colors.purpleAccent.shade400': Colors.purpleAccent.shade400,
  'Colors.purpleAccent.shade700': Colors.purpleAccent.shade700,
  'Colors.deepPurple': Colors.deepPurple,
  'Colors.deepPurple.shade50': Colors.deepPurple.shade50,
  'Colors.deepPurple.shade100': Colors.deepPurple.shade100,
  'Colors.deepPurple.shade200': Colors.deepPurple.shade200,
  'Colors.deepPurple.shade300': Colors.deepPurple.shade300,
  'Colors.deepPurple.shade400': Colors.deepPurple.shade400,
  'Colors.deepPurple.shade500': Colors.deepPurple.shade500,
  'Colors.deepPurple.shade600': Colors.deepPurple.shade600,
  'Colors.deepPurple.shade700': Colors.deepPurple.shade700,
  'Colors.deepPurple.shade800': Colors.deepPurple.shade800,
  'Colors.deepPurple.shade900': Colors.deepPurple.shade900,
  'Colors.deepPurpleAccent': Colors.deepPurpleAccent,
  'Colors.deepPurpleAccent.shade100': Colors.deepPurpleAccent.shade100,
  'Colors.deepPurpleAccent.shade200': Colors.deepPurpleAccent.shade200,
  'Colors.deepPurpleAccent.shade400': Colors.deepPurpleAccent.shade400,
  'Colors.deepPurpleAccent.shade700': Colors.deepPurpleAccent.shade700,
  'Colors.indigo': Colors.indigo,
  'Colors.indigo.shade50': Colors.indigo.shade50,
  'Colors.indigo.shade100': Colors.indigo.shade100,
  'Colors.indigo.shade200': Colors.indigo.shade200,
  'Colors.indigo.shade300': Colors.indigo.shade300,
  'Colors.indigo.shade400': Colors.indigo.shade400,
  'Colors.indigo.shade500': Colors.indigo.shade500,
  'Colors.indigo.shade600': Colors.indigo.shade600,
  'Colors.indigo.shade700': Colors.indigo.shade700,
  'Colors.indigo.shade800': Colors.indigo.shade800,
  'Colors.indigo.shade900': Colors.indigo.shade900,
  'Colors.indigoAccent': Colors.indigoAccent,
  'Colors.indigoAccent.shade100': Colors.indigoAccent.shade100,
  'Colors.indigoAccent.shade200': Colors.indigoAccent.shade200,
  'Colors.indigoAccent.shade400': Colors.indigoAccent.shade400,
  'Colors.indigoAccent.shade700': Colors.indigoAccent.shade700,
  'Colors.blue': Colors.blue,
  'Colors.blue.shade50': Colors.blue.shade50,
  'Colors.blue.shade100': Colors.blue.shade100,
  'Colors.blue.shade200': Colors.blue.shade200,
  'Colors.blue.shade300': Colors.blue.shade300,
  'Colors.blue.shade400': Colors.blue.shade400,
  'Colors.blue.shade500': Colors.blue.shade500,
  'Colors.blue.shade600': Colors.blue.shade600,
  'Colors.blue.shade700': Colors.blue.shade700,
  'Colors.blue.shade800': Colors.blue.shade800,
  'Colors.blue.shade900': Colors.blue.shade900,
  'Colors.blueAccent': Colors.blueAccent,
  'Colors.blueAccent.shade100': Colors.blueAccent.shade100,
  'Colors.blueAccent.shade200': Colors.blueAccent.shade200,
  'Colors.blueAccent.shade400': Colors.blueAccent.shade400,
  'Colors.blueAccent.shade700': Colors.blueAccent.shade700,
  'Colors.lightBlue': Colors.lightBlue,
  'Colors.lightBlue.shade50': Colors.lightBlue.shade50,
  'Colors.lightBlue.shade100': Colors.lightBlue.shade100,
  'Colors.lightBlue.shade200': Colors.lightBlue.shade200,
  'Colors.lightBlue.shade300': Colors.lightBlue.shade300,
  'Colors.lightBlue.shade400': Colors.lightBlue.shade400,
  'Colors.lightBlue.shade500': Colors.lightBlue.shade500,
  'Colors.lightBlue.shade600': Colors.lightBlue.shade600,
  'Colors.lightBlue.shade700': Colors.lightBlue.shade700,
  'Colors.lightBlue.shade800': Colors.lightBlue.shade800,
  'Colors.lightBlue.shade900': Colors.lightBlue.shade900,
  'Colors.lightBlueAccent': Colors.lightBlueAccent,
  'Colors.lightBlueAccent.shade100': Colors.lightBlueAccent.shade100,
  'Colors.lightBlueAccent.shade200': Colors.lightBlueAccent.shade200,
  'Colors.lightBlueAccent.shade400': Colors.lightBlueAccent.shade400,
  'Colors.lightBlueAccent.shade700': Colors.lightBlueAccent.shade700,
  'Colors.cyan': Colors.cyan,
  'Colors.cyan.shade50': Colors.cyan.shade50,
  'Colors.cyan.shade100': Colors.cyan.shade100,
  'Colors.cyan.shade200': Colors.cyan.shade200,
  'Colors.cyan.shade300': Colors.cyan.shade300,
  'Colors.cyan.shade400': Colors.cyan.shade400,
  'Colors.cyan.shade500': Colors.cyan.shade500,
  'Colors.cyan.shade600': Colors.cyan.shade600,
  'Colors.cyan.shade700': Colors.cyan.shade700,
  'Colors.cyan.shade800': Colors.cyan.shade800,
  'Colors.cyan.shade900': Colors.cyan.shade900,
  'Colors.cyanAccent': Colors.cyanAccent,
  'Colors.cyanAccent.shade100': Colors.cyanAccent.shade100,
  'Colors.cyanAccent.shade200': Colors.cyanAccent.shade200,
  'Colors.cyanAccent.shade400': Colors.cyanAccent.shade400,
  'Colors.cyanAccent.shade700': Colors.cyanAccent.shade700,
  'Colors.teal': Colors.teal,
  'Colors.teal.shade50': Colors.teal.shade50,
  'Colors.teal.shade100': Colors.teal.shade100,
  'Colors.teal.shade200': Colors.teal.shade200,
  'Colors.teal.shade300': Colors.teal.shade300,
  'Colors.teal.shade400': Colors.teal.shade400,
  'Colors.teal.shade500': Colors.teal.shade500,
  'Colors.teal.shade600': Colors.teal.shade600,
  'Colors.teal.shade700': Colors.teal.shade700,
  'Colors.teal.shade800': Colors.teal.shade800,
  'Colors.teal.shade900': Colors.teal.shade900,
  'Colors.tealAccent': Colors.tealAccent,
  'Colors.tealAccent.shade100': Colors.tealAccent.shade100,
  'Colors.tealAccent.shade200': Colors.tealAccent.shade200,
  'Colors.tealAccent.shade400': Colors.tealAccent.shade400,
  'Colors.tealAccent.shade700': Colors.tealAccent.shade700,
  'Colors.green': Colors.green,
  'Colors.green.shade50': Colors.green.shade50,
  'Colors.green.shade100': Colors.green.shade100,
  'Colors.green.shade200': Colors.green.shade200,
  'Colors.green.shade300': Colors.green.shade300,
  'Colors.green.shade400': Colors.green.shade400,
  'Colors.green.shade500': Colors.green.shade500,
  'Colors.green.shade600': Colors.green.shade600,
  'Colors.green.shade700': Colors.green.shade700,
  'Colors.green.shade800': Colors.green.shade800,
  'Colors.green.shade900': Colors.green.shade900,
  'Colors.greenAccent': Colors.greenAccent,
  'Colors.greenAccent.shade100': Colors.greenAccent.shade100,
  'Colors.greenAccent.shade200': Colors.greenAccent.shade200,
  'Colors.greenAccent.shade400': Colors.greenAccent.shade400,
  'Colors.greenAccent.shade700': Colors.greenAccent.shade700,
  'Colors.lightGreen': Colors.lightGreen,
  'Colors.lightGreen.shade50': Colors.lightGreen.shade50,
  'Colors.lightGreen.shade100': Colors.lightGreen.shade100,
  'Colors.lightGreen.shade200': Colors.lightGreen.shade200,
  'Colors.lightGreen.shade300': Colors.lightGreen.shade300,
  'Colors.lightGreen.shade400': Colors.lightGreen.shade400,
  'Colors.lightGreen.shade500': Colors.lightGreen.shade500,
  'Colors.lightGreen.shade600': Colors.lightGreen.shade600,
  'Colors.lightGreen.shade700': Colors.lightGreen.shade700,
  'Colors.lightGreen.shade800': Colors.lightGreen.shade800,
  'Colors.lightGreen.shade900': Colors.lightGreen.shade900,
  'Colors.lightGreenAccent': Colors.lightGreenAccent,
  'Colors.lightGreenAccent.shade100': Colors.lightGreenAccent.shade100,
  'Colors.lightGreenAccent.shade200': Colors.lightGreenAccent.shade200,
  'Colors.lightGreenAccent.shade400': Colors.lightGreenAccent.shade400,
  'Colors.lightGreenAccent.shade700': Colors.lightGreenAccent.shade700,
  'Colors.lime': Colors.lime,
  'Colors.lime.shade50': Colors.lime.shade50,
  'Colors.lime.shade100': Colors.lime.shade100,
  'Colors.lime.shade200': Colors.lime.shade200,
  'Colors.lime.shade300': Colors.lime.shade300,
  'Colors.lime.shade400': Colors.lime.shade400,
  'Colors.lime.shade500': Colors.lime.shade500,
  'Colors.lime.shade600': Colors.lime.shade600,
  'Colors.lime.shade700': Colors.lime.shade700,
  'Colors.lime.shade800': Colors.lime.shade800,
  'Colors.lime.shade900': Colors.lime.shade900,
  'Colors.limeAccent': Colors.limeAccent,
  'Colors.limeAccent.shade100': Colors.limeAccent.shade100,
  'Colors.limeAccent.shade200': Colors.limeAccent.shade200,
  'Colors.limeAccent.shade400': Colors.limeAccent.shade400,
  'Colors.limeAccent.shade700': Colors.limeAccent.shade700,
  'Colors.yellow': Colors.yellow,
  'Colors.yellow.shade50': Colors.yellow.shade50,
  'Colors.yellow.shade100': Colors.yellow.shade100,
  'Colors.yellow.shade200': Colors.yellow.shade200,
  'Colors.yellow.shade300': Colors.yellow.shade300,
  'Colors.yellow.shade400': Colors.yellow.shade400,
  'Colors.yellow.shade500': Colors.yellow.shade500,
  'Colors.yellow.shade600': Colors.yellow.shade600,
  'Colors.yellow.shade700': Colors.yellow.shade700,
  'Colors.yellow.shade800': Colors.yellow.shade800,
  'Colors.yellow.shade900': Colors.yellow.shade900,
  'Colors.yellowAccent': Colors.yellowAccent,
  'Colors.yellowAccent.shade100': Colors.yellowAccent.shade100,
  'Colors.yellowAccent.shade200': Colors.yellowAccent.shade200,
  'Colors.yellowAccent.shade400': Colors.yellowAccent.shade400,
  'Colors.yellowAccent.shade700': Colors.yellowAccent.shade700,
  'Colors.amber': Colors.amber,
  'Colors.amber.shade50': Colors.amber.shade50,
  'Colors.amber.shade100': Colors.amber.shade100,
  'Colors.amber.shade200': Colors.amber.shade200,
  'Colors.amber.shade300': Colors.amber.shade300,
  'Colors.amber.shade400': Colors.amber.shade400,
  'Colors.amber.shade500': Colors.amber.shade500,
  'Colors.amber.shade600': Colors.amber.shade600,
  'Colors.amber.shade700': Colors.amber.shade700,
  'Colors.amber.shade800': Colors.amber.shade800,
  'Colors.amber.shade900': Colors.amber.shade900,
  'Colors.amberAccent': Colors.amberAccent,
  'Colors.amberAccent.shade100': Colors.amberAccent.shade100,
  'Colors.amberAccent.shade200': Colors.amberAccent.shade200,
  'Colors.amberAccent.shade400': Colors.amberAccent.shade400,
  'Colors.amberAccent.shade700': Colors.amberAccent.shade700,
  'Colors.orange': Colors.orange,
  'Colors.orange.shade50': Colors.orange.shade50,
  'Colors.orange.shade100': Colors.orange.shade100,
  'Colors.orange.shade200': Colors.orange.shade200,
  'Colors.orange.shade300': Colors.orange.shade300,
  'Colors.orange.shade400': Colors.orange.shade400,
  'Colors.orange.shade500': Colors.orange.shade500,
  'Colors.orange.shade600': Colors.orange.shade600,
  'Colors.orange.shade700': Colors.orange.shade700,
  'Colors.orange.shade800': Colors.orange.shade800,
  'Colors.orange.shade900': Colors.orange.shade900,
  'Colors.orangeAccent': Colors.orangeAccent,
  'Colors.orangeAccent.shade100': Colors.orangeAccent.shade100,
  'Colors.orangeAccent.shade200': Colors.orangeAccent.shade200,
  'Colors.orangeAccent.shade400': Colors.orangeAccent.shade400,
  'Colors.orangeAccent.shade700': Colors.orangeAccent.shade700,
  'Colors.deepOrange': Colors.deepOrange,
  'Colors.deepOrange.shade50': Colors.deepOrange.shade50,
  'Colors.deepOrange.shade100': Colors.deepOrange.shade100,
  'Colors.deepOrange.shade200': Colors.deepOrange.shade200,
  'Colors.deepOrange.shade300': Colors.deepOrange.shade300,
  'Colors.deepOrange.shade400': Colors.deepOrange.shade400,
  'Colors.deepOrange.shade500': Colors.deepOrange.shade500,
  'Colors.deepOrange.shade600': Colors.deepOrange.shade600,
  'Colors.deepOrange.shade700': Colors.deepOrange.shade700,
  'Colors.deepOrange.shade800': Colors.deepOrange.shade800,
  'Colors.deepOrange.shade900': Colors.deepOrange.shade900,
  'Colors.deepOrangeAccent': Colors.deepOrangeAccent,
  'Colors.deepOrangeAccent.shade100': Colors.deepOrangeAccent.shade100,
  'Colors.deepOrangeAccent.shade200': Colors.deepOrangeAccent.shade200,
  'Colors.deepOrangeAccent.shade400': Colors.deepOrangeAccent.shade400,
  'Colors.deepOrangeAccent.shade700': Colors.deepOrangeAccent.shade700,
  'Colors.brown': Colors.brown,
  'Colors.brown.shade50': Colors.brown.shade50,
  'Colors.brown.shade100': Colors.brown.shade100,
  'Colors.brown.shade200': Colors.brown.shade200,
  'Colors.brown.shade300': Colors.brown.shade300,
  'Colors.brown.shade400': Colors.brown.shade400,
  'Colors.brown.shade500': Colors.brown.shade500,
  'Colors.brown.shade600': Colors.brown.shade600,
  'Colors.brown.shade700': Colors.brown.shade700,
  'Colors.brown.shade800': Colors.brown.shade800,
  'Colors.brown.shade900': Colors.brown.shade900,
  'Colors.grey': Colors.grey,
  'Colors.grey.shade50': Colors.grey.shade50,
  'Colors.grey.shade100': Colors.grey.shade100,
  'Colors.grey.shade200': Colors.grey.shade200,
  'Colors.grey.shade300': Colors.grey.shade300,
  'Colors.grey.shade400': Colors.grey.shade400,
  'Colors.grey.shade500': Colors.grey.shade500,
  'Colors.grey.shade600': Colors.grey.shade600,
  'Colors.grey.shade700': Colors.grey.shade700,
  'Colors.grey.shade800': Colors.grey.shade800,
  'Colors.grey.shade900': Colors.grey.shade900,
  'Colors.blueGrey': Colors.blueGrey,
  'Colors.blueGrey.shade50': Colors.blueGrey.shade50,
  'Colors.blueGrey.shade100': Colors.blueGrey.shade100,
  'Colors.blueGrey.shade200': Colors.blueGrey.shade200,
  'Colors.blueGrey.shade300': Colors.blueGrey.shade300,
  'Colors.blueGrey.shade400': Colors.blueGrey.shade400,
  'Colors.blueGrey.shade500': Colors.blueGrey.shade500,
  'Colors.blueGrey.shade600': Colors.blueGrey.shade600,
  'Colors.blueGrey.shade700': Colors.blueGrey.shade700,
  'Colors.blueGrey.shade800': Colors.blueGrey.shade800,
  'Colors.blueGrey.shade900': Colors.blueGrey.shade900,
  'Colors.white': Colors.white,
  'Colors.white10': Colors.white10,
  'Colors.white12': Colors.white12,
  'Colors.white24': Colors.white24,
  'Colors.white30': Colors.white30,
  'Colors.white38': Colors.white38,
  'Colors.white54': Colors.white54,
  'Colors.white60': Colors.white60,
  'Colors.white70': Colors.white70,
  'Colors.black': Colors.black,
  'Colors.black12': Colors.black12,
  'Colors.black26': Colors.black26,
  'Colors.black38': Colors.black38,
  'Colors.black45': Colors.black45,
  'Colors.black54': Colors.black54,
  'Colors.black87': Colors.black87,
});
